apiVersion: v1
kind: Service
metadata:
  name: whishlist-frontend
spec:
  selector:
    app: whishlist
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whishlist-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whishlist
  template:
    metadata:
      labels:
        app: whishlist
    spec:
      containers:
      - name: whishlist
        image: europe-central2-docker.pkg.dev/calm-drive-303114/whishlist/whishlist-frontend
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
        env:
          - name: PG_CONNSTRING
            valueFrom:
              configMapKeyRef:
                name: whishlist-db-connstr
                key: PG_CONNSTRING

