apiVersion: apps/v1
kind: Deployment
metadata:
  name: whishlist-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whishlist
  template:
    metadata:
      labels:
        app: whishlist
    spec:
      containers:
      - name: postgres
        image: postgres:10.12
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: whishlist-db
        volumeMounts:
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: initdb
        configMap:
          name: postgres-initdb-config
      - name: data
        persistentVolumeClaim:
          claimName: whishlist-db-pvc-nimble
