apiVersion: v1
kind: ConfigMap
metadata:
  name: whishlist-db-connstr
  labels:
    app: whishlist
data:
  PG_CONNSTRING: postgres://postgres_user:postgres@whishlist-db/postgres_db?sslmode=disable
---
apiVersion: v1
kind: Service
metadata:
  name: whishlist-frontend
spec:
  selector:
    app: whishlist
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whishlist-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whishlist
  template:
    metadata:
      labels:
        app: whishlist
    spec:
      containers:
      - name: whishlist
        image: mpolski/whishlist:1.0
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
        env:
          - name: PG_CONNSTRING
            valueFrom:
              configMapKeyRef:
                name: whishlist-db-connstr
                key: PG_CONNSTRING

